
import = [
  "~/.config/alacritty/themes/themes/kanagawa_wave.toml"
]

[font]
normal = { family = "JetbrainsMono Nerd Font" }
size = 15
offset = { y = 3 }

[window]
decorations = "Buttonless"
padding = { x = 10, y = 10 }

[shell]
program = "/opt/homebrew/bin/fish"

