theme = "kanagawa"
# theme = "darkvoid"

[editor]
true-color = true
line-number = "relative"
bufferline = "always"
rulers = [120]
cursorline = true
completion-trigger-len = 1
scroll-lines = 1

[editor.whitespace.render]
newline = "all"

[editor.indent-guides]
render = true
character = "▏"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = true

[editor.statusline]

left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = false

# Keymap things
[keys.normal]
C-h = "select_prev_sibling"
C-j = "shrink_selection"
C-k = "expand_selection"
C-l = "select_next_sibling"

C-y = ["scroll_up"]
C-e = ["scroll_down"]
esc = ["collapse_selection", "keep_primary_selection"]
g = { d = "goto_definition", D = ["vsplit", "goto_definition"], j = "goto_last_line", k = "goto_file_start" }
ret = ["goto_word"]

# Kakoune inspired keymapping
E = ["extend_next_word_end"]
W = ["extend_next_word_start"]
B = ["extend_prev_word_end"]
K = "extend_line_up"
J = "extend_line_down"
H = "extend_char_left"
L = "extend_char_right"
'{' = ["select_mode", "goto_prev_paragraph"]
'}' = ["select_mode", "goto_next_paragraph"]
x = ["select_mode", "extend_line_below"]

[keys.select]
# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
'{' = "goto_prev_paragraph"
'}' = "goto_next_paragraph"
E = ["extend_next_word_end"]
W = ["extend_next_word_start"]
B = ["extend_prev_word_end"]
K = "extend_line_up"
J = "extend_line_down"
H = "extend_char_left"
L = "extend_char_right"

[keys.select.g]
j = "goto_last_line"
k = "goto_file_start"

[keys.normal.G]
J = ["select_mode", "goto_last_line"]
K = ["select_mode", "goto_file_start"]
L = ["select_mode", "goto_line_end"]
H = ["select_mode", "goto_line_start"]

[keys.select.G]
J = "goto_last_line"
K = "goto_file_start"
L = "goto_line_end"
H = "goto_line_start"

[keys.normal.space]
w   = ":write"
q   = ":quit"
c   = ":buffer-close"
C   = ":config-reload"
',' = ":config-open"
e = ":sh hx-utils explorer > /dev/null"
# Zen mode
z = ":toggle gutters.line-numbers.min-width 24 3"

# Legacy pickers
b = "no_op"
j = "no_op"

# lsp actions no move under space.l
S = "no_op"
s = "no_op"
r = ":rl"
d = "no_op"
D = "no_op"
a = "no_op"
F = "no_op"

# swap command palette
'?' = "no_op"
space = "command_palette"

[keys.select.space]
w   = ":write"
q   = ":quit"
c   = ":buffer-close"
C   = ":config-reload"
',' = ":config-open"
e = ":sh hx-utils explorer > /dev/null"
# Zen mode
z = ":toggle gutters.line-numbers.min-width 24 3"

# Legacy pickers
b = "no_op"
j = "no_op"

# lsp actions no move under space.l
S = "no_op"
s = "no_op"
r = ":rl"
d = "no_op"
D = "no_op"
a = "no_op"
F = "no_op"

# swap command palette
'?' = "no_op"
space = "command_palette"

# Terminal actions
[keys.normal.space.t]
l = ":sh tsm popup lazygit"
f = ":sh tsm popup"
j = ":sh tsm popup lazyjj"
r = ":sh tsm popup serpl"
# Bottom terminal
b = ":sh winmux sp fish > /dev/null"
B = ":sh hx-utils blame > /dev/null"

# LSP commans
[keys.normal.space.l]
r = "rename_symbol"
a = "code_action"
s = "symbol_picker"
S = "workspace_symbol_picker"
d = "diagnostics_picker"
D = "workspace_diagnostics_picker"

[keys.normal.space.o]

# Harpoon mode
l = ":sh hx-utils harpoon list"
a = ":sh hx-utils harpoon add"
d = ":sh hx-utils harpoon remove"
e = ":sh hx-utils harpoon edit"
1 = ":sh winmux -p 1 sp 'hx-utils harpoon open 1' > /dev/null"
2 = ":sh winmux -p 1 sp 'hx-utils harpoon open 2' > /dev/null"
3 = ":sh winmux -p 1 sp 'hx-utils harpoon open 3' > /dev/null"
4 = ":sh winmux -p 1 sp 'hx-utils harpoon open 4' > /dev/null"
5 = ":sh winmux -p 1 sp 'hx-utils harpoon open 5' > /dev/null"
6 = ":sh winmux -p 1 sp 'hx-utils harpoon open 6' > /dev/null"
7 = ":sh winmux -p 1 sp 'hx-utils harpoon open 7' > /dev/null"
8 = ":sh winmux -p 1 sp 'hx-utils harpoon open 8' > /dev/null"
9 = ":sh winmux -p 1 sp 'hx-utils harpoon open 9' > /dev/null"

[keys.normal.";"]
q = ["goto_line_start", "select_mode", "move_next_long_word_end", ":pipe-to qf_hx_open", "collapse_selection", "normal_mode"]

# Find actions
[keys.normal.space.f]
b = "buffer_picker"
f = "file_picker"
g = ":sh hx-utils git-files > /dev/null"
w = ":sh hx-utils grep > /dev/null"
d = ":sh hx-utils git-changed-files > /dev/null"
p = "file_picker_in_current_buffer_directory"
j = "jumplist_picker"
e = "@:e <C-r>%<C-w>"
x = "@:sh rm <C-r>%"


[keys.insert]
C-space = "completion"
S-tab = "unindent"
esc = ["collapse_selection", "normal_mode"]

