theme = "kanagawa"

[editor]
true-color = true
line-number = "relative"
bufferline = "always"
rulers = [120]
cursorline = true
cursorcolumn = true

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
#left = ["mode", "spinner"]
center = ["file-name"]
# right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]

separator = ""
left = ["mode", "file-base-name", "version-control", "file-modification-indicator"]
right = ["diagnostics", "spinner", "file-encoding", "file-type", "file-line-ending",  "spacer", "position-percentage", "position"]


# separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.normal]
C-y = ["scroll_up"]
C-e = ["scroll_down"]
esc = ["collapse_selection", "keep_primary_selection"]
g = { d = "goto_definition", D = ["vsplit", "goto_definition"] }
# C-p = [":new", ":insert-output lf-pick", ":theme default", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":theme catppuccin_mocha"]

[keys.normal.space]
w   = ":write"
q   = ":quit"
c   = ":config-reload"
',' = ":config-open"

[keys.insert]
C-space = "completion"
S-tab = "unindent"
