# [[language]]
# name = "typescript"
# auto-format = true
# formatter = { command = "prettier", args = ["--parser", "typescript"] }

# language-servers = ["typescript-language-server", "eslint"]

# [language-server.eslint]
# args = ["--stdio"]
# command = "vscode-eslint-language-server"

# [language-server.eslint.config]
# format = true
# nodePath = ""
# onIgnoredFiles = "off"
# packageManager = "yarn"
# quiet = false
# rulesCustomizations = []
# run = "onType"
# useESLintClass = false
# validate = "on"
# codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
# codeActionOnSave = { mode = "all" }
# experimental = { }
# problems = { shortenToSingleLine = false }
# workingDirectory = { mode = "auto" }