"$schema" = 'https://starship.rs/config-schema.json'

format = "[~](bright-purple) $username $git_branch$git_state$shell $fill $cmd_duration 󰇝 $time$nodejs\n[~](bright-purple) ${custom.spaced_dir} $character"

[username]
format = "[$user]($style)"
style_user = 'light-white'
show_always = true

[git_branch]
format = "[ ](bold white) [ $branch]($style)"
style = 'bright-purple'

[fill]
symbol = ' '

[time]
format = "$time"
time_format = "%a at %-l:%M %p"
use_12hr = true
disabled = false

[shell]
fish_indicator = 'fish'
disabled = false
format = '[  ](bold white) [$indicator]($style)'
style = 'bright-purple'

[nodejs]
format = " [](green) [$version](dimmed white)"
version_format ="${raw}"

# [directory]
# format = '[ $path]($style)[$read_only]($read_only_style) '
# truncation_length = 8
# fish_style_pwd_dir_length = 40
# style = "bright-cyan"

[custom.spaced_dir]
command = "~/.bin/spaced-path"
format = "[ $output]($style)"
style = "bright-blue"
when = true

[cmd_duration]
min_time = 1
show_milliseconds = true
format = '[$duration]($style)'
style = 'dimmed white'

[git_status]
style = 'bright-red'

[character]
error_symbol = "[~](bold red)"
success_symbol = "[~](bold green)"
