"$schema" = 'https://starship.rs/config-schema.json'

format = """[~](#BFA8BF) $username $git_branch$git_state$shell $fill $cmd_duration ${custom.day} [at](bold white) ${custom.time} $nodejs
[~](#BFA8BF) ${custom.spaced_dir} $character
"""

[username]
format = "[$user]($style)"
style_user = 'light-white'
show_always = true

[git_branch]
format = "[ ](bold white) [ $branch]($style)"
style = '#BFA8BF'

[fill]
symbol = ' '

# [time]
# format = "$time"
# time_format = "%a at %-l:%M %p"
# use_12hr = true
# disabled = false

[shell]
fish_indicator = 'fish'
disabled = false
format = '[  ](bold white) [$indicator]($style)'
style = '#BFA8BF'

[nodejs]
format = " [](green) [$version](dimmed white) "
version_format ="${raw}"

# [directory]
# format = '[ $path]($style)[$read_only]($read_only_style) '
# truncation_length = 8
# fish_style_pwd_dir_length = 40
# style = "bright-cyan"

[cmd_duration]
min_time = 1
show_milliseconds = true
format = '[$duration]($style) 󰇝'
style = 'dimmed white'

[git_status]
style = 'bright-red'

[character]
error_symbol = "[~](bold red)"
success_symbol = "[~](bold green)"


[custom.spaced_dir]
command = """p=${PWD/#$HOME/home}; p=${p#/}; echo "$p" | sed 's|/| / |g'"""
format = "[ $output]($style)"
shell = "bash"
style = "#B6D6F2"
when = true

[custom.day]
command = """date '+%a'"""
shell = "bash"
format = "[${output}](dimmed white)"
when = true

[custom.time]
command = """date '+%-l:%M %p'"""
shell = "bash"
format = "[${output}](dimmed white)"
when = true
