[language_ids]
javascript = "javascriptreact"
typescript = "typescriptreact"

[language_server.tsserver]
filetypes = ["javascript", "typescript"]
roots = ["package.json", "tsconfig.json", "jsconfig.json", ".git", ".hg"]
command = "typescript-language-server"
args = ["--stdio"]

[language_server.tailwindcss]
filetypes = ["javascript", "typescript"]
roots = ["tailwind.config.ts", "tailwind.config.js"]
command = "tailwindcss-language-server"
args = ["--stdio"]
settings_section = "_"

[language_server.tailwindcss.settings._]
editor = {}

[language_server.markdown]
filetypes = ["markdown"]
roots = [".marksman.toml"]
command = "marksman"
args = ["server"]

# [language_server.eslint]
# filetypes = ["javascript", "typescript"]
# roots = [".eslintrc", ".eslintrc.json"]
# command = "vscode-eslint-language-server"
# args = ["--stdio"]
# settings_section = "_"

# [language_server.eslint.settings._]
# codeActionsOnSave = { mode = "all", "source.fixAll.eslint" = true }
# format = { enable = true }
# nodePath = ""
# quiet = false
# rulesCustomizations = []
# run = "onType"
# validate = "on"
# experimental = {}
# problems = { shortenToSingleLine = false }

# [language_server.eslint.settings._.codeAction]
# disableRuleComment = { enable = true, location = "separateLine" }
# showDocumentation = { enable = false }
