
# gleam
[language.gleam.grammar.source.git]
url = "https://github.com/gleam-lang/tree-sitter-gleam"
pin = "bcf9c45b56cbe46e9dac5eee0aee75df270000ac"

[language.gleam.grammar]
path = "src"
compile = "cc"
compile_args = ["-c", "-fpic", "../parser.c", "../scanner.c", "-I", ".."]
compile_flags = ["-O3"]
link = "cc"
link_args = ["-shared", "-fpic", "parser.o", "scanner.o", "-o", "gleam.so"]
link_flags = ["-O3"]

[language.gleam.queries]
path = "runtime/queries/gleam"

[language.gleam.queries.source.git]
url = "https://github.com/helix-editor/helix"
pin = "2cadec0b1182332338a5a1cc3062776f834d8835"


# Embedded template
[language.embedded-template.grammar.source.git]
url = "https://github.com/tree-sitter/tree-sitter-embedded-template"
pin = "38d5004a797298dc42c85e7706c5ceac46a3f29f"

[language.embedded-template.grammar]
path = "src"
compile = "cc"
compile_args = ["-c", "-fpic", "../parser.c", "-I", ".."]
compile_flags = ["-O3"]
link = "cc"
link_args = ["-shared", "-fpic", "parser.o", "-o", "embedded-template.so"]
link_flags = ["-O3"]

[language.embedded-template.queries.source.local]
path = "/Users/yukai/Library/Application Support/kak-tree-sitter/additional/ejs"

[language.embedded-template.queries]
path = "."

# [language.erb.grammar.source.git]
# url = "https://github.com/tree-sitter/tree-sitter-embedded-template"
# pin = "38d5004a797298dc42c85e7706c5ceac46a3f29f"

# [language.erb.grammar]
# path = "src"
# compile = "cc"
# compile_args = ["-c", "-fpic", "../parser.c", "-I", ".."]
# compile_flags = ["-O3"]
# link = "cc"
# link_args = ["-shared", "-fpic", "parser.o", "-o", "erb.so"]
# link_flags = ["-O3"]

# [language.erb.queries.source.local]
# path = "/Users/yukai/Library/Application Support/kak-tree-sitter/additional/erb"

# [language.erb.queries]
# path = "."
